language: scala
scala:
- 2.12.2
script:
- sbt dist
- sbt debian:packageBin
deploy:
  provider: releases
  api_key:
    secure: GyteeqgmMckvjbYdNdJs8RxlbPE1Qa/CPMqolptLxGRiUZDXOLLFXspAj9SfwpKZHCBG2Vs/39xb5x/CAHbzrkPnZ4Nv8Uf8v8hPshBFBouU+orzLeUlZT4ONf723OgsTCEt1SRjQLXF1D6lZM28awGndA5uG0Pox8QS2jfcd9EkfI3jvi5y9SQaxKdbielxAfDBCuSCdbGdRig6a/cd7i9Bh2TEasqUt7bF8YlZldxMNUrJ5nKYmIgQAWX52kgaQzC+nzr2Rm5ql6llzIJYedApYwlAG3gD9beGm3jt/vNaw8eTD4O5TGfPScuIUyTIfy/J8wFyw+lEwWfLXT8PVxR/lbUH0VmDv1kPxBXIMkjQIWCS8vZ5qeZJ+szScZb0Z4DI4bN6OmYGO1G4ETz4b7acAVLjWy/T4ZMo1w+rQIvFnZv1Wf1FuXS1MyP8Y/8gHZmEMYUZjLqA11VT2LkHHqgCUGCucp0MgPcqwM9WM1CQuI31Wjg6ThDy2HSmK1pTJ3IikrTP4u/sWuI0Qc5pok4xS1supptawRo1qqkgWd+hO+haBwvmansJN2zjowMrYbz1mGslTldXKgwBWe1CxQPf/Tdl+yRcK2OPaBXYnH4TVYtnA2+DVAsQ01xy39O2cboa2zUnGp/fzCMjIT3i0G6d/DZrBkeRdekpAZ6tj3k=
  file:
  - target/*deb
  - target/universal/*.zip
  on:
    repo: Polyjapan/ji-shop
